### ISSUE TITLE
(Request) Add option to disable Legend on Add-WordLineChart

### ISSUE THREAD

**Issue by thecloudjedi** [EvotecIT/PSWriteWord#12]
Thank you for creating all of this. Its been a huge help with a project I am working on. 

Under the Add-WordLineChart cmdlet, could you add an option to disable the Legend? I am getting some messy results in the graph
![cpuchart](https://user-images.githubusercontent.com/42980922/45054446-02c86480-b05b-11e8-8e00-327c3dc1feff.png)

**Comment by PrzemyslawKlys** [comment]
Hi,

Added `-NoLegend` switch. Whether you leave `ChartLegendPosition -ChartLegendOverlay` doesn't matter. It will be skipped if `-NoLegend` is used. Make sure to use diff series. It seems if you try to reuse series it breaks word. 

![image](https://user-images.githubusercontent.com/15063294/45059267-b6e9df80-b09b-11e8-82a8-f997592d701f.png)

```
Import-Module PSWriteWord #-Force

$FilePath = "$Env:USERPROFILE\Desktop\PSWriteWord-Example-CreateCharts2.docx"

$WordDocument = New-WordDocument $FilePath
Add-WordText -WordDocument $WordDocument -Text 'Line Chart Example #1' `
    -FontSize 15 `
    -Color Blue `
    -Bold $true -HeadingType Heading1 -Supress $True

Add-WordLineChart -WordDocument $WordDocument -ChartName 'My finances' -Names 'Today', 'Yesterday', 'Two days ago' -Values 1050.50, 2000, 20000 -ChartLegendPosition Bottom -ChartLegendOverlay $false


Add-WordText -WordDocument $WordDocument -Text 'Line Chart Example #2' `
    -FontSize 15 `
    -Color Blue `
    -Bold $true -HeadingType Heading1 -Supress $True


$Series1 = Add-WordChartSeries -ChartName 'One'  -Names 'Today', 'Yesterday', 'Two days ago' -Values 1050.50, 2000, 20000
$Series2 = Add-WordChartSeries -ChartName 'Two'  -Names 'Today', 'Yesterday', 'Two days ago' -Values 3000, 2000, 1000

Add-WordLineChart -WordDocument $WordDocument -ChartName 'My finances' -ChartLegendPosition Bottom -ChartLegendOverlay $false -ChartSeries $Series1, $Series2

Add-WordText -WordDocument $WordDocument -Text 'Line Chart Example #3 - No legend' `
    -FontSize 15 `
    -Color Blue `
    -Bold $true -HeadingType Heading1 -Supress $True

Add-WordText -WordDocument $WordDocument -Text "Keep in mind that you need to define new series for each new chart. Otherwise errors will occur..." -Supress $True

$Series3 = Add-WordChartSeries -ChartName 'One'  -Names 'Today', 'Yesterday', 'Two days ago' -Values 1050.50, 2000, 20000
$Series4 = Add-WordChartSeries -ChartName 'Two'  -Names 'Today', 'Yesterday', 'Two days ago' -Values 3000, 2000, 1000

Add-WordLineChart -WordDocument $WordDocument -ChartName 'My finances1' -ChartSeries $Series3, $Series4 -NoLegend


Save-WordDocument $WordDocument -Supress $True

### Start Word with file
Invoke-Item $FilePath
```

I've updated all 3 examples and changed this for all 3 charts. I've published new version to PSGallery.

**Comment by PrzemyslawKlys** [comment]
BTw don't be surprised that PSWriteWord downloads PSSharedGoods when you use (`Update-Module PSwriteword`). I've extracted functions I use in all my modules to stop having to update it over and over if i change something. I plan to expand this library with useful things that somehow end up in all of my scripts.

**Comment by thecloudjedi** [comment]
You are a champion. Thank you. I will test this out today

**Comment by PrzemyslawKlys** [comment]
I'm assuming this works fine. Closing.
