### ISSUE TITLE
Unable to find type [InsertWhere]

### ISSUE THREAD

**Issue by KimChr** [EvotecIT/PSWriteWord#13]
Thank you very much for this great module!

When I call Add-WordParagraph or Add-WordPageBreak, fx in your example: Example-CreateWord1.ps1, I get this error: 

`Unable to find type [InsertWhere].`
`At C:\Temp\PSWriteWord-Master\Public\PSWordParagraphOther.ps1:72 char:26`
`+         [alias('Insert')][InsertWhere] $InsertWhere = [InsertWhere]:: ...`
`+                          ~~~~~~~~~~~~~`
`    + CategoryInfo          : InvalidOperation: (InsertWhere:TypeName) [], RuntimeException`
`    + FullyQualifiedErrorId : TypeNotFound`

What do I do wrong?

Best regards
Kim B. Christensen

**Comment by KimChr** [comment]
Yes I do.
Other commands ,like Add-WordText works fine.
And yes I do use PowerShell 5.1.

**Comment by KimChr** [comment]
I forgot to tell you that I also had problems with Add-WordText. 
It could not find [UnderlineStyle[]], but I changed it to [Xceed.Words.NET.UnderlineStyle[]] 
and also others to include Xceed.Words.NET and then it worked.
But it doesn't work if I change [InsertWhere] to [Xceed.Words.NET.InsertWhere]

**Comment by PrzemyslawKlys** [comment]
Well you're essentially trying to use Xceed net enums and not PSWriteWord enums, while they may work it's not how it's supposed to be. It seems like Enums from the Enums folder aren't loading for you. You sure you got latest version?

**Comment by KimChr** [comment]
For some reason the Enums folder was missing in my test..... It works now
Thank you very much for your quick help.

/Kim

**Comment by PrzemyslawKlys** [comment]
Great! Thanks for using PSWriteWord :-)
