### ISSUE TITLE
error msg in Set-WordTableRowMergeCells line 102 NULL-Methode

### ISSUE THREAD

**Issue by uwefranke** [EvotecIT/PSWriteWord#15]
Import-Module pswriteword -Force
$FilePath = "$Env:USERPROFILE\Desktop\test111.docx"

$WordDocument = New-WordDocument $FilePath
$Table1 = new-WordTable -WordDocument $WordDocument -NrRows 3 -NrColumns 3
Add-WordTableCellValue -Table $Table1 -Row 0 -Column 0  -Value "test"
Set-WordTableRowMergeCells -Table $Table1 -RowNr 0 -ColumnNrStart 0 -ColumnNrEnd 2 
Save-WordDocument -WordDocument $WordDocument

file: PSWordTableRows.ps1
Set-WordTableRowMergeCells line 101 work with:
for ($paragraph = 1; $paragraph **-lt** $Table.Rows[$RowNr].Cells[$ColumnNrStart].Paragraphs.Count; $paragraph++) {

**Comment by PrzemyslawKlys** [comment]
Hey,

Thanks for reporting. 

It's fixed. Please `Update-Module PSWriteWord` 

Btw. Take a look at Add-WordTable. It's far superior to New-WordTable as it can take an Object and make a table out of it.
