### ISSUE TITLE
Get-WordDocument fails to load document with []'s in the filename

### ISSUE THREAD

**Issue by zaepho** [EvotecIT/PSWriteWord#18]
The following code generates a Warning that the file does not exist and an error failing to open the document. The document does exist at that path ($File below is from a Get-ChildItem result). If the []'s are removed from the filename then Get-WordDocument loads the file as expected with no other changes.

```Powershell
$Doc = Get-WordDocument -FilePath $File.FullName -Verbose -ErrorAction Stop
```

Errors/Warnings
```
WARNING: Get-WordDocument - Document doesn't exists in path C:\Users\kevin\Documents\FyrsoftAccel\FyrSoftAccelerators\Documentation\Input\[Customer Name] - SCOM SAC Infrastructure Design 3.5.docx. Terminating loading word from file.
1/9/2019 10:38:51       ERROR   Failed to open Document C:\Users\kevin\Documents\FyrsoftAccel\FyrSoftAccelerators\Documentation\Input\[Customer Name] - SCOM SAC Infrastructure Design 3.5.docx
```

**Comment by PrzemyslawKlys** [comment]
Thanks for reporting. Will see if this can be addressed. Most likely needs escaping of `[]` when passing it to DLL.

**Comment by PrzemyslawKlys** [comment]
I've published a new version. 

```
Update-Module PSWriteWord
```

Should work. Let me know.

**Comment by zaepho** [comment]
Works exactly as expected! Thanks for the speedy resolution!
