### ISSUE TITLE
Add-WordTable missing 1st row in Array of PSCustomObject

### ISSUE THREAD

**Issue by PenguinPaws** [EvotecIT/PSWriteWord#2]
When I was following the Add-WordTable examples, and trying to figure out how to use my own array as input, I noticed a bug.

Since your 1st row (Row 0) is for the header, you forgot to increment the corresponding index when pulling values from the array into the table.

So in the example code below, the table will be **missing the row for "Joe", Cat Lover, 32**.

(Also, is there any way to specify an order to the columns?)

```
$myitems = @(
    [pscustomobject]@{name="Joe"; age=32; info="Cat lover"},
    [pscustomobject]@{name="Sue"; age=29; info="Dog lover"},
    [pscustomobject]@{name="Jason"; age=42; info="Food lover"}
)

Import-Module PSWriteWord #-Force

$FilePath = "C:\2\PSWriteWord-x.docx"
$WordDocument = New-WordDocument $FilePath
Add-WordTable -WordDocument $WordDocument -Table $myitems -Design 'ColorfulList' #-Verbose
Save-WordDocument $WordDocument
```

**Comment by PrzemyslawKlys** [comment]
Thanks for reporting this. Will fix. I have also started working on tables a bit more to add more functionality to it and support multiple cases. I estimate the dev version should be today later on.

**Comment by PrzemyslawKlys** [comment]
Should be fixed. Please get new version. I've also added your example into examples (hope you don't mind). I'm using all examples as part of testing if the output is as expected. I had to change few things in new version to support other stuff so -Table is now -DataTable and -Table has other meaning. There are dozen other options now as well. Let me know how it goes.

**Comment by PrzemyslawKlys** [comment]
As for the order you need to use [ordered]. Otherwise you may get different results (as seen in one of the examples).

**Comment by PenguinPaws** [comment]
Thanks so much for fixing this so fast :)
Your PS Module is simply amazing, and I love it!

And of course, I don't mind you adding my examples to yours. Also, thanks for the tip of using [ordered] when defining my array. It does exactly what I needed.

Is it intentional that -FontSize is not a valid parameter on the text inside the table? I wanted to double check that I didn't overlook something before adding that as a feature request.

**Comment by PrzemyslawKlys** [comment]
Make a feature request and I'll try to add it.
