### ISSUE TITLE
Table columncount limit

### ISSUE THREAD

**Issue by leadlxx** [EvotecIT/PSWriteWord#20]
I found that the number of table columns can only be limited to 5，is a bug？

**Comment by PrzemyslawKlys** [comment]
No, you can overwrite the limit with MaximumColumns parameter. It's there to prevent overflow of columns. From my testing 5-7 columns is a max what you can fit on an A4 page.

**Comment by leadlxx** [comment]
> No, you can overwrite the limit with MaximumColumns parameter. It's there to prevent overflow of columns. From my testing 5-7 columns is a max what you can fit on an A4 page.

thanks
