### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by tom2win** [EvotecIT/PSWriteWord#21]
Hi, thank you for this great Module!

In German we have "Umlaute" like äöü and so on. I did'nt found any way to handle this with your Module. 
Can you give me a hint or fix somethin to do this?

Thank you very much.

**Comment by PrzemyslawKlys** [comment]
Yes,

Make sure to use UTF-8 with BOM as enoding of your .ps1 file.

![image](https://user-images.githubusercontent.com/15063294/56865118-9673ea00-69ca-11e9-99dd-e468db01d24c.png)

**Comment by tom2win** [comment]
I don't know how to use your Screenshot.

Within the Script i tried with this Lines, but no Success:
[System.Text.Encoding]::UTF8
$OutputEncoding = [System.Text.Encoding]::UTF8
$PSDefaultParameterValues = @{ '*:Encoding' = 'utf8' }

How can i set the File or into the Script to UTF-8 with BOM?

Thanks for your Help.

**Comment by PrzemyslawKlys** [comment]
No, You have to use editor such as VSCode and set encoding of a file that way. Script has nothing to do with it.

Download VSCode, download PowerShell Extension (you will thank me for that) and then simply change encoding of a file.

**Comment by tom2win** [comment]
Ok, thank you very much. I already work with vscode for a longer time, and it was a fight to change the encoding. But with "save file with encoding" it worked well. Nice.
