### ISSUE TITLE
Using New-WordDocument fails with Object Reference not set

### ISSUE THREAD

**Issue by dbaduck** [EvotecIT/PSWriteWord#22]
[40] # New-WordDocument -FilePath c:\temp\mydoc
format-default : Object reference not set to an instance of an object.
    + CategoryInfo          : NotSpecified: (:) [format-default], NullReferenceException
    + FullyQualifiedErrorId : System.NullReferenceException,Microsoft.PowerShell.Commands.FormatDefaultCommand

Fresh install from PowerShell Gallery with Install-Module PsWriteWord

**Comment by PrzemyslawKlys** [comment]
```
$WordDocument = New-WordDocument -FilePath ...
```

Take a look at examples. You need to use a variable to get the data from New-WordDocument.

**Comment by dbaduck** [comment]
Very nice. I looked at the Get-Help but not the examples.  Thanks.

**Comment by PrzemyslawKlys** [comment]
alternatively you can try to use different approach using Documentimo. 

https://github.com/EvotecIT/Documentimo

In this article, somewhere in the middle Documentimo is described and an example is shown: https://evotec.xyz/what-do-we-say-to-writing-active-directory-documentation/

**Comment by DarkLite1** [comment]
Having the same issue. Used the example from the [docs](https://evotec.xyz/hub/scripts/pswriteword-powershell-module/#:~:text=This%20PowerShell%20Module%20allows%20you,t%20require%20any%20COM%20objects.):

```powershell
Import-Module PSWriteWord
$FilePath = "$Env:USERPROFILE\Desktop\PSWriteWord-Example-CreateWord1.docx"
$WordDocument = New-WordDocument $FilePath
```
When checking the variable `$WordDocument` for a value we see this:
![image](https://user-images.githubusercontent.com/10828570/136028491-777531fc-8266-45d1-aef6-744197c8d815.png)

Fresh install from the PowerShell Gallery on PS 5.1.

**Comment by PrzemyslawKlys** [comment]
Don't check the variable? :) It should work

**Comment by PrzemyslawKlys** [comment]
Using new-worddocuement the very first object is kind of broken. If you add something it will work. Using get-worddocument should work properly from the start

**Comment by DarkLite1** [comment]
Maybe the errors should be suppressed with a `try/catch` clause. It seems like things are broken when a user sees errors. It would be more clean if this could be avoided. We're opting to not use this module for now. Thanks anyway for the work you put into this.

**Comment by PrzemyslawKlys** [comment]
There's not much I can do. The error isn't coming from the function - but in your code. 

```powershell
Import-Module PSWriteWord
$FilePath = "$Env:USERPROFILE\Desktop\PSWriteWord-Example-CreateWord1.docx"
$WordDocument = New-WordDocument $FilePath
$WordDocument.Paragraphs
```

This doesn't give you any errors. It just works. You then go and add things to it and it just works. What you did is check the newly created object $WordDocument in your own code, and you got an error. This means it's out of my control. 

That's how the DocX object behaves 

![image](https://user-images.githubusercontent.com/15063294/136158158-55729dc8-9bde-4614-a0a6-a25938fe038e.png)

This doesn't happen when you load the Word - it should display whatever you want

```powershell
### Before running this script make sure to run Example-CreateWord first
$FilePath = "$Env:USERPROFILE\Desktop\PSWriteWord-Example-CreateWord1.docx"
$FilePath = ".\Templates\CV-Template.docx"

$WordDocument = Get-WordDocument -FilePath $FilePath
$WordDocument
```

DocX library is out of date. The new version is licensed in a way that I believe will be bad for the community. I have something in works that works cross-platform but it's not yet public, but it won't be having as many features as PSWriteWord has. I could probably update library to newest version but the license they use is going to be bad.

**Comment by DarkLite1** [comment]
Thank you for getting back to me and to explain how it works. One would just expect the returned object form a Word file to hold properties that can be populated. Given your example this doesn't seem to be the case. 

We're actually trying to populate a Word template with values from an Excel file. Currently we're thinking about using the plan Word object on a Windows 10 client to do this.

**Comment by PrzemyslawKlys** [comment]
That's pretty much doable with 2 modules:
1. Read Excel
2. Read Word

```powershell
### Before running this script make sure to run Example-CreateWord first
$FilePathTemplate = "$PSScriptRoot\Templates\CV-WithTextReplacement.docx"

$WordDocument = Get-WordDocument -FilePath $FilePathTemplate

foreach ($Paragraph in $WordDocument.Paragraphs) {
    # You can display text as seen by PSWriteWord
    $Paragraph.Text
    # Case sensitive
    $Paragraph.ReplaceText('Job Title', 'CEO of EVOTEC')
    $Paragraph.ReplaceText('School Name 1st', 'Oh my school')
    $Paragraph.ReplaceText('School Name 2nd', 'Oh my school 2')
    # While word shows NAME HERE, actually it's Name HERE
    $Paragraph.ReplaceText('Name HERE', 'Przemysław Kłys')
    $Paragraph.ReplaceText('PHONE_NUMBER', '+48 500 500 500')
}

Save-WordDocument -WordDocument $WordDocument -FilePath "$PSSCriptRoot\Output\CV-WithReplacedText.docx" -OpenDocument -Supress $true
```

Just fix the loop to include whatever you have in excel and you're home.
