### ISSUE TITLE
Adding Border to Table

### ISSUE THREAD

**Issue by LoniBoy** [EvotecIT/PSWriteWord#27]
Hi,

i have the problem that there is no table-border when i create it with your module.
With "open Office" on the Server i can see borders. On my local computer(normal word) there are missing.

The Set-WordTable -Border/type or "Set-WordTableBorder" does not work(or i dont understand the syntax).

Thanks.

**Comment by PrzemyslawKlys** [comment]
Take a look at Example-Table4. 

Consider using Add-WordTable instead. It's much easier to deal with tables. You're right that it's a bit counter intuitive. Most likely I will be updating this behavior in a new version at some point for easier custom table building.

**Comment by LoniBoy** [comment]
This is not working.

![error](https://user-images.githubusercontent.com/38783307/59442411-75d8e580-8dfa-11e9-8bc3-9e8fe8f6efab.png)

**Comment by PrzemyslawKlys** [comment]
Install-Module PSWriteWord -Force -AllowPrerelease 

Try this one. I've started modifying examples to match new word

**Comment by LoniBoy** [comment]
Then he Says that the "AllowPrerelease" is an unknown parameter.

BTW.: On my computer it works with PowerShell-Version 5.1.XXXXX
The affected server have Version 4.0

Do you think it helps to update framework including powershell?

**Comment by PrzemyslawKlys** [comment]
Hi,

1. https://evotec.xyz/install-module-a-parameter-cannot-be-found-that-matches-parameter-name-allowprerelease/

2. But I have already released 1.0 version. So just Update-Module PSWriteWord and try again. 

As for updating PS, well I don't test on anything below 5.1. Its possible things won't be working on PS4 4.0 as I have never checked.

**Comment by LoniBoy** [comment]
Hi,

the command "install-module" and "Get-module" are Part of 
- Windows 10 or newer
- Windows Server 2016 or newer
- WMF 5.0
- PowerShell v6

So the good old Server 2012r2 with the basic WMF 4/PowerShell 4 is not able to use all functions in PSWriteWord.
I will install WMF5 tomorrow and try it again.
I will let you know the results.
Thanks!

**Comment by LoniBoy** [comment]
With the new PowerShell the Module works much better!
It seems PSWriteWord need some Framework-Assemblies from WMF5
However...
Problem is solved! :)

**Comment by PrzemyslawKlys** [comment]
I'm glad. I've never tested on older versions ;-) Sorry for that. 5.1+ is my support ;)
