### ISSUE TITLE
Error in Code

### ISSUE THREAD

**Issue by LoniBoy** [EvotecIT/PSWriteWord#28]
Hi, its me again :)

i think i found some problems in the code.

![image](https://user-images.githubusercontent.com/38783307/60331271-92495600-9994-11e9-89ba-2ce24e07ff4d.png)

Here in your "PSWordPicture" in the module the "{ return $data }" and the { return } should be exchanged. Otherwise the "supress" will not work.

And the Add-WordPicture does not work until i change the "-path"(in my script) to "$FilePathImage"...
As far as i can see this line in your "PSwordPicture" should be:

- $Image = $WordDocument.AddImage($ImagePath)

I hope this helps

**Comment by PrzemyslawKlys** [comment]
Hi,

are you sure you use newest version? 

![image](https://user-images.githubusercontent.com/15063294/60334058-e5bea280-999a-11e9-97f9-912d43e46daa.png)


The supress one i'm fixing now.

**Comment by PrzemyslawKlys** [comment]
Please do

```
Update-Module PSWriteWord
```

I've published a new version which fixes the Suppress part. The other part was already fixed in 1.0.0.

**Comment by PrzemyslawKlys** [comment]
Just to add, don't be afraid to open issues or mention problems. That's what the issues are for ;-) Thank you!
