### ISSUE TITLE
Add-WordTable cannot take input from a HashTable 

### ISSUE THREAD

**Issue by PenguinPaws** [EvotecIT/PSWriteWord#3]
I cannot seem to get the contents of a HashTable to be displayed in a Table.

**What I expect**: A table with 1 column for my keys, and 1 column for my values
**What actually happens**: A table with no values in it. Only the first line has the values "Name" and "Value".

(As an aside, I found that an array of System.Object can be displayed in a table, but I honestly would rather avoid that as the syntax is far too verbose for my liking)

Code to demonstrate this:
```
$hash = @{}
$hash.add("HQ-1", "5.54.546")
$hash.add("EUR-1", "6.0.0.1")
$hash.add("HQ-2", "5.6")
$hash.add("EUR-2", "6.1.5")
$hash.add("EUR-3", "6.2")

$obj = New-Object System.Object
$obj | Add-Member -type NoteProperty -name Name -Value "Ryan_PC"
$obj | Add-Member -type NoteProperty -name Manufacturer -Value "Dell"
$obj | Add-Member -type NoteProperty -name ProcessorSpeed -Value "3 Ghz"
$obj | Add-Member -type NoteProperty -name Memory -Value "6 GB"

$myObject2 = New-Object System.Object
$myObject2 | Add-Member -type NoteProperty -name Name -Value "Doug_PC"
$myObject2 | Add-Member -type NoteProperty -name Manufacturer -Value "HP"
$myObject2 | Add-Member -type NoteProperty -name ProcessorSpeed -Value "2.6 Ghz"
$myObject2 | Add-Member -type NoteProperty -name Memory -Value "4 GB"

$myObject3 = New-Object System.Object
$myObject3 | Add-Member -type NoteProperty -name Name -Value "Julie_PC"
$myObject3 | Add-Member -type NoteProperty -name Manufacturer -Value "Compaq"
$myObject3 | Add-Member -type NoteProperty -name ProcessorSpeed -Value "2.0 Ghz"
$myObject3 | Add-Member -type NoteProperty -name Memory -Value "2.5 GB"

$myArray = @($obj, $myobject2, $myObject3)



Import-Module PSWriteWord #-Force

$FilePath = "L:\RICHIE\Desktop\2\PSWriteWord-x.docx"
$WordDocument = New-WordDocument $FilePath
Add-WordTable -WordDocument $WordDocument -Table $hash -Design 'ColorfulList' #-Verbose
Add-WordTable -WordDocument $WordDocument -Table $myArray -Design 'ColorfulList' #-Verbose

Save-WordDocument $WordDocument
Invoke-Item $FilePath
```

**Comment by PrzemyslawKlys** [comment]
It should be fixed now. As with your other report I've taken this as example and added into examples. Again please notice -Table has different use now so use -DataTable. Essentially go thru new Examples from tables and you will understand why... :-)

**Comment by PenguinPaws** [comment]
Hey! Sorry, I didn't get a chance to try it until today.

Can confirm - it works now (& of course, after using the parameter name as -DataTable)

I like that "-Autofit Window" flag that you mentioned in the examples too.

Is there an option to specify the relative width of the columns, or will they always be distributed evenly, by default?
(My case scenario is that my column 1, the FQDN of the servers are far longer than the content of hte 2nd column)

**Comment by PrzemyslawKlys** [comment]
That can be added I think. Make a feature request and sometime next week I'll fix it.
