### ISSUE TITLE
Unable to find type [InsertBeforeOrAfter] :(

### ISSUE THREAD

**Issue by ThomasLukowski** [EvotecIT/PSWriteWord#31]
I'm still receiving "Unable to find type [InsertBeforeOrAfter]" using the latest version of PSWinDocumentation.AD and Documentimo:

C:\Users\***\Documents\WindowsPowerShell\Modules\PSWriteWord\1.0.2\PSWriteWord.psm1:820 char:9
+   param([InsertBeforeOrAfter] $Table,
+         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (InsertBeforeOrAfter:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
or
Unable to find type [InsertBeforeOrAfter].
At C:\Users\***\Documents\WindowsPowerShell\Modules\PSWriteWord\1.0.2\PSWriteWord.psm1:2996 char:72
+ ... elineByPropertyName, ValueFromPipeline)][InsertBeforeOrAfter] $Paragr ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (InsertBeforeOrAfter:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
 
Tried to replace Xceed.Words.NET.dll v1.3.0 with v1.2.0 but the error still exsists.
Any ideas? :)

**Comment by PrzemyslawKlys** [comment]
Are you using Import-Module PSWriteWord -Force before? Are you using PSGallery version?

**Comment by tlukowsk** [comment]
Yes, i'm using PSGallery Version. ...upps will try to force PSWriteWord before.

**Comment by PrzemyslawKlys** [comment]
Problem is related to Namespaces. For PSWriteWord to work you need to have this executed.
https://www.powershellgallery.com/packages/PSWriteWord/1.0.2/Content/PSWriteWord.Usings.ps1

When you execute Import-module PSWriteWord it should read .psd1 file in which it says:
```
    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = 'PSWriteWord.Usings.ps1'
```

So that means execute that ps1 file before running PSWriteWord. Let me know if Import-Module PSWriteWord helps. 

https://www.powershellgallery.com/packages/PSWriteWord/1.0.2/Content/PSWriteWord.psd1

**Comment by ThomasLukowski** [comment]
Ok. Thanks a lot for your quick support!

**Comment by PrzemyslawKlys** [comment]
Did it work?

**Comment by ThomasLukowski** [comment]
I don't know yet. It's a large test environment and I think it still running over the whole ad... I let you know about the results, I promise!
#pozdrokatowice

**Comment by ThomasLukowski** [comment]
Hi! A word file was finally created. But it delievers only sites and services information. All others are empty... I'm running PoSh elevated as enterprise admin.

**Comment by PrzemyslawKlys** [comment]
Hi, this is not really an issue of PSWriteWord. 

Please use: https://evotec.xyz/what-do-we-say-to-writing-active-directory-documentation/ 

Could it be related to your configuration file? Sections enabled? Please review your configuration and maybe open an issue related to product you're using?
