### ISSUE TITLE
How to add custom Table Styles

### ISSUE THREAD

**Issue by elcorewin** [EvotecIT/PSWriteWord#41]
Hello,

Under Add-WordTable -Design parameter has option "Custom", Is there an  example on how to use the -Design Custom ? 

`Add-WordTable -WordDocument $WordDocument -DataTable $DataTable -Design Custom`

Also if using Custom is possible, how do i define the Custom design?

**Comment by PrzemyslawKlys** [comment]
Hi,

This is one enum values so not really sure how to use it. I'm not a word expert. But what you can do is use an example: https://github.com/EvotecIT/PSWriteWord/blob/master/Examples/Example-Tables4.ps1 but building your own custom stuff is going to be pain :-)

**Comment by elcorewin** [comment]
Hi @PrzemyslawKlys , Thanks!, 

Can I use custom Hex or RGB code for color properties as stated in Example you posted?

**Comment by PrzemyslawKlys** [comment]
Using my commands probably not. Overall, to be honest I don't know. I have created this like 2 years ago and haven't touched it since. Probably you would need to dive into sources and see what I do there. I don't think you can use custom colors but I may be wrong here.

Here's the C# code that I "translate" to PowerShell:
- https://github.com/xceedsoftware/DocX/blob/master/Xceed.Document.NET/Src/Table.cs
- https://github.com/xceedsoftware/DocX/blob/master/Xceed.Document.NET/Src/_Enumerations.cs
- https://github.com/xceedsoftware/DocX/tree/master/Xceed.Words.NET.Examples/Samples/Table

You will be most interested in examples from there. Any reason why you want to waste time building your own custom design ? :)

From a quick look custom colors are no go.

**Comment by elcorewin** [comment]
So basically I am trying to automate some documentation, however the pre-design Word template has specific format for Heading Styles which I am able to apply using the Word template.

However it seems the Table styles doesn't work the same way how Heading Styles do.

Long story short, looking for custom colors so i can match the table style which the template uses.

Thanks, appreciate your help :)

**Comment by PrzemyslawKlys** [comment]
Well, you can probably overwrite just header rather than doing the whole table from scratch. It's possible to add a table and edit it post-factum. Basically, once you create $table with add-wordtable you can get that table and display it's settings/change stuff around etc.

**Comment by elcorewin** [comment]
Thanks @PrzemyslawKlys for your help once again...

**Comment by mdcaddic** [comment]
Not sure you can 'create' a custom table design with PSWriteWord but I did eventually work out how to do this by going back to the xceed site.
Process is: 
1. Have a word document that has all of your styles (including custom tables types) already in it. Make sure the custom table design name does not include spaces.
2. Delete all the content so you still have all of the styles and then save
3. $CustomTableDesign = 'Name-Of-The-Custom-Table-Design'
4. $wordDocument = Get-WordDocument -FilePath $newDoc.FullName to open the doc
5. $table = Add-WordTable -WordDocument $wordDocument -DataTable $objData -Design Custom
6. $table.CustomTableDesignName = $CustomTableDesign
7. $wordDocument.Save()

**Comment by GiriSudh** [comment]
Thanks @mdcaddic . Can you please let me know how can I get the Custom Table Design which I have created manually ?

**Comment by GiriSudh** [comment]
A big Thank you to @mdcaddic . 
After couple of brainstormings, trial and errors -- it is found that the table style name is *CASE SENSITIVE* and now it is working like a charm for me.

**Comment by PrzemyslawKlys** [comment]
Glad this was resolved. Just to clarify - what @mdcaddic proposed was a simple .docx creation even where you create stuff, delete content, and just use it as a template. There are no special requirements here or anything that Xceed does differently.

**Comment by Nizamc** [comment]
@mdcaddic and @PrzemyslawKlys the above solution is not appropriate.
when we edit existing default table style ( Plain table) in word document and save it as template then only it is applying the style. when we defined new Table style is not applying. Could you help me in resolving this issue.

seems some issue wit

**Comment by mdcaddic** [comment]
I assume when you say save it as a template you are referring to the table style. Absolutely make sure that the table style name you are using does not have spaces. That caused me a bunch of heartache for a while. For the document ensure you are saving the document as a docx and then open using Get-WordDocument.

**Comment by Nizamc** [comment]
@mdcaddic,

I can confirm the the style name i have created in word document is same as we have in following script. refer attached word document where i have created table style and imported data in to table.
the style is not applied what we have specified in script.

[New_TEMP.docx](https://github.com/EvotecIT/PSWriteWord/files/4609128/New_TEMP.docx)




$FilePath = "C:\ps\New_TEMP.docx"

#Call the document from above filepath
$WordDocument = Get-WordDocument -FilePath $FilePath


#Technical Data
$hotfixes = Get-HotFix | select HotFixID, InstalledOn


$CustomTableDesign='Test'

$table = Add-WordTable -WordDocument $wordDocument -DataTable $hotfixes -Design Custom
$table.CustomTableDesignName = $CustomTableDesign
$wordDocument.Save()
#Invoke-Item $FilePath

**Comment by mdcaddic** [comment]
@Nizamc I ran your code in ISE and got the table you were expecting (white writing on green in header). Sorry, I can't produce an error.
