### ISSUE TITLE
not found option to Embed Excel into Word- Icon 

### ISSUE THREAD

**Issue by Nizamc** [EvotecIT/PSWriteWord#42]
Hi All,

can Some one guide me how to Embed an Excel file or Html file into PsWriteWord document as an icon. Tried most of the option not found relevant. request to kindly guide. 
![test](https://user-images.githubusercontent.com/33017994/83345098-d70c0880-a32c-11ea-8769-44ef173685cd.JPG)

**Comment by Nizamc** [comment]
Hi all,

any update to my query

**Comment by PrzemyslawKlys** [comment]
At the moment it's not possible AFYIK.
