### ISSUE TITLE
Add-WordTable with -Transpose wrong order

### ISSUE THREAD

**Issue by atiedemann** [EvotecIT/PSWriteWord#44]
Hello @EvotecIT,

first of all, thanks for your great PowerShell Module. :-)
I have a question. When I use Add-WordTable iwith parameter -Transpose and I submit a datatable, the module or what ever order the first column alphabetically not like in the datatable.
When I use the function without -Transpose it is working fine.

Does anyone know to solve this?

Thanks
Arne

**Comment by PrzemyslawKlys** [comment]
Actually I'll fix it now.

**Comment by PrzemyslawKlys** [comment]
Update-module PSWriteWord should fix this issue

**Comment by atiedemann** [comment]
This is nice and I test it today and it is working fine.
Thanks a lot and have a nice day.
