### ISSUE TITLE
PSWriteWord generates empty word file

### ISSUE THREAD

**Issue by johannes-z** [EvotecIT/PSWriteWord#45]
I'm using the latest released version of PSWriteWord (https://github.com/EvotecIT/PSWriteWord/tree/v1.1.8), and an example snippet but I only get an empty file:

```ps1
Import-Module $PSScriptRoot\PSWriteWord.psd1 -Force

$T1 = [PSCustomObject] @{
  Test   = 1
  Test2  = 7
  Ole    = 'bole'
  Trolle = 'A'
  Alle   = 'sd'
}

$T2 = [ordered] @{
  Test   = 1
  Test2  = 7
  Ole    = 'bole'
  Trolle = 'A'
  Alle   = 'sd'
}


$FilePath = "$Env:USERPROFILE\Desktop\PSWriteWord-Example-Tables9.docx"

$WordDocument = New-WordDocument $FilePath

Add-WordText -WordDocument $WordDocument -Text "Before" -Supress $true
Add-WordTable -WordDocument $WordDocument -DataTable $T1 -Design ColorfulGrid -Supress $true
Add-WordText -WordDocument $WordDocument -Text "After" -Supress $true
Add-WordTable -WordDocument $WordDocument -DataTable $T1 -Transpose -Design ColorfulGrid -Supress $true

Add-WordText -WordDocument $WordDocument -Text "Before T2" -Supress $true
Add-WordTable -WordDocument $WordDocument -DataTable $T2 -Design ColorfulGrid -Supress $true
Add-WordText -WordDocument $WordDocument -Text "After T2" -Supress $true
Add-WordTable -WordDocument $WordDocument -DataTable $T2 -Transpose -Design ColorfulGrid -Supress $true

Save-WordDocument $WordDocument -Language 'en-US' -Supress $True -OpenDocument
```

I think this problem is due to using PowerShell 6.2 instead of 5.*

**Comment by PrzemyslawKlys** [comment]
Yes. It's not supported on 6 or 7. This is due to Xceed Library not supporting this in free version. THey only support Net Standard in pay version. I've been asking them to add support for Core to community edition, but failed.

**Comment by johannes-z** [comment]
Ah Ok. That's too bad. It's also a really hard error to track down. Maybe adding a Warning or Exception to PSWriteWord could help to avoid this in the future. Feel free to close this issue then.

**Comment by PrzemyslawKlys** [comment]
I'll add compatible editions in next release (PSD1):

```
    CompatiblePSEditions       = @('Desktop')
```

Which should prevent installing/importing from the gallery I hope.

**Comment by PrzemyslawKlys** [comment]
The thing is, I actually had tested it with the trial version and it was working. So it's in theory possible to get pay version running with PSWriteWord.

**Comment by PrzemyslawKlys** [comment]
Btw.

```
Works only on Windows (as NET CORE is not supported by DLL) - until Xceed ads that to their version. Which will take a while for the free version to have (if ever).
Works only on PowerShell 5.1 (not tested on PowerShell 6.0 with Windows compatibility pack)
``` 

It's in the requirements in README :-) And I just confirmed it doesn't work with windows compatibility in PS 7. Sorry.
