### ISSUE TITLE
module is not working in 2019 server encountering error "Get-WordDocument - Document: F:\server.docx Error: Unable to find type [Xceed.Words.NET.DocX]"

### ISSUE THREAD

**Issue by Nizamc** [EvotecIT/PSWriteWord#48]
module is not working in 2019 server encountering error "Get-WordDocument - Document: F:\server.docx Error: Unable to find type [Xceed.Words.NET.DocX]"

it is workign on my laptop windows 10 but same code is not working in server os I.e 2019 do it has any limitations or do we missed any modules kindly guide me.

**Comment by PrzemyslawKlys** [comment]
Installing from PSGallery directly? Powershell 5.1?

**Comment by Nizamc** [comment]
@PrzemyslawKlys  any update please..

**Comment by Nizamc** [comment]
installed modules using offline method (copying Module directories to "$Env:ProgramFiles\WindowsPowerShell\Modules") and running Command Import-module ******
As the server doesn't have internet access in my Lab
the PS version is 5.1

**Comment by Nizamc** [comment]
in addition to my previous comments i have downloaded module directories (PSWriteWord,Connectimo,PSWriteColor,PSSharedGoods)on my laptop 
copied all these directories to "C:\ProgramFiles\WindowsPowerShell\Modules" of server 2019
then run the command import-module (name pf above directories)

**Comment by PrzemyslawKlys** [comment]
You're doing it wrong. Use Save-Module PSWriteWord command on your desktop. Get it to download stuff for you. Copy everything from the path it created. That's it.
