### ISSUE TITLE
Get-WordDocument causes Powershell 5.1 window to exit

### ISSUE THREAD

**Issue by zaldre** [EvotecIT/PSWriteWord#52]
Hi there,

First time trying to use your module and test some basic functionality. I was expecting that using

``` Get-WordDocument -filepath .\test.docx ```

would return an object containing details about the file, but actual behaviour seems to just exit the console.

Powershell 5.1
Windows 10 Pro vers  10.0.19042 (Build 19042)

**Comment by PrzemyslawKlys** [comment]
It's my mistake, there were Exit commands when something went wrong in those cmdlets. I don't know what I was thinking when I wrote it.

**Comment by PrzemyslawKlys** [comment]
This is now fixed, a new version was released. Thank you for reporting.
