### ISSUE TITLE
Get-WordDocument only works when passing full path to file

### ISSUE THREAD

**Issue by zaldre** [EvotecIT/PSWriteWord#53]
Hi again,

Thank you for fixing the issue with the "exit" commands. Get-WordDocument now works when passing the full path to file, but does not work with relative paths

Tested on both Win10 and Server 2016

``` PS C:\users\myusername\Desktop Get-WordDocument .\test.docx
WARNING: Get-WordDocument - Document: .\test.docx Error: Exception calling "Load" with "1" argument(s): "File could not
 be found .\test.docx"
PS C:\Users\snowpea\Desktop> Get-WordDocument test.docx
WARNING: Get-WordDocument - Document: test.docx Error: Exception calling "Load" with "1" argument(s): "File could not
be found test.docx"
PS C:\Users\snowpea\Desktop> WARNING: Get-WordDocument - Document: .\test.docx Error: Exception calling "Load" with "1" argument(s): "File could not found test.docx"

PS C:\Users\snowpea\Desktop> Get-WordDocument C:\users\snowpea\desktop\test.docx

FilePath                 : C:\users\snowpea\desktop\test.docx
MarginTop                : 72
MarginBottom             : 56
MarginLeft               : 42
MarginRight              : 42
MarginHeader             : 35
MarginFooter             : 25
MirrorMargins            : False




```

Get-WordDocument "$($pwd.path)\test.docx" also works.

**Comment by zaldre** [comment]
Based on my very quick assessment of your code and the error i'm seeing,  i assume that it's failing on line 16 

``` $WordDocument = [Xceed.Words.NET.DocX]::Load($FilePath)```

I think it could potentially be solved by doing this


```$FileAbsolutePath = (Get-ChildItem $FilePath).fullname
   $WordDocument = [Xceed.Words.NET.DocX]::Load($FileAbsolutePath)```

**Comment by PrzemyslawKlys** [comment]
Feel free to make a PR. I've never, ever used relative paths, in any of my projects - hence why it was never tested and never bothered to fix it. I would say you should either use Get-Item or Resolve-Path or Convert-Path.

I use `Convert-Path` in [PSWritePDF](https://github.com/EvotecIT/PSWritePDF) as it was failing for network drives from what I remember and someone suggested it. 

https://github.com/EvotecIT/PSWritePDF/blob/cf14d56e1d1c8916643c5f57341dba9099a57253/Public/Get-PDF.ps1#L8-L8

Not sure if it works for relative paths. Care to make PR and do some tests?

**Comment by PrzemyslawKlys** [comment]
This has been fixed in https://github.com/EvotecIT/PSWriteWord/commit/80897c0a1cd67b0135d33716b677ed414ce07994
