### ISSUE TITLE
Brackets { problem - no executing

### ISSUE THREAD

**Issue by oliwex** [EvotecIT/PSWriteWord#56]
If brackets is in:
code
{
            code
}

style then it gives an error

**Comment by PrzemyslawKlys** [comment]
You have to be a lot more specific - i dont' have a clue what you mean.

**Comment by oliwex** [comment]
Code Example:

    #Użytkownicy
    DocNumbering -Text 'Spis użytkowników' -Level 0 -Type Numbered -Heading Heading1 {
        
        DocText {
            "Ta część zawiera spis użytkowników w każdej jednostce organizacyjnej"
        }
    
        $OUs=(Get-ADOrganizationalUnit -Filter *).DistinguishedName
        
        foreach($OU in $OUs)
        {
            DocNumbering -Text $OU -Level 1 -Type Numbered -Heading Heading1 {
     
            $UserInfo=(Get-UserFromOU -OUpath $OU -extended:$false)
                foreach($User in $UserInfo)
                {
                    $hashtable=ConvertTo-Hashtable -Object $User
                    DocTable -DataTable $hashtable -Design ColorfulGridAccent5 -AutoFit Window -OverwriteTitle 'User'
                    DocText -LineBreak
                    #po userze
                }
            }
        }
        DocText -LineBreak
    }

#######################################
And then if i code like this:

DocNumbering -Text 'Spis użytkowników' -Level 0 -Type Numbered -Heading Heading1 
{
 DocText 
{
            "Ta część zawiera spis użytkowników w każdej jednostce organizacyjnej"
        }
<# something #>
 IT gives me an error:

The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.
At C:\Program Files\WindowsPowerShell\Modules\PSWriteWord\1.1.9\PSWriteWord.psm1:596 char:39
+         Content                   = & $Content
+                                       ~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression

**Comment by PrzemyslawKlys** [comment]
Impossible to reproduce. Show me something that breaks and is reproducible without spending a ton of time. I have no functions that you mention and from the code above that supposedly isn't working - nothing stands out.
