### ISSUE TITLE
DocTable gets only hashtable

### ISSUE THREAD

**Issue by oliwex** [EvotecIT/PSWriteWord#58]
$hashtable=ConvertTo-Hashtable -Object $User
DocTable -DataTable $hashtable -Design ColorfulGridAccent5 -AutoFit Window -OverwriteTitle $User.Name

DocTable gets only a hashtable as datatable parameter. So when i want to create DocTable i must write my own function to generate hashtable from psobject and then create doctable.

or
give me code example of generating doctable from pscustom object

**Comment by PrzemyslawKlys** [comment]
```powershell
Documentimo -FilePath $PSScriptRoot\Documentimo-BasicList.docx {
    $CustomObject =  [PSCustomObject] @{ Name = 'Test 1'; SomeValue = 1 }

    DocTable -DataTable $CustomObject
} -Open
```

Works just fine.

**Comment by oliwex** [comment]
So as i see the List is for pscustom object and the table is for hashtable

**Comment by oliwex** [comment]
Sorry...tested it and i must convert into hashtable firstly and then create table.
If not, then the table is transposed in word document

**Comment by PrzemyslawKlys** [comment]
If you run the example above it works just fine - not sure what you mean.

**Comment by oliwex** [comment]
$OUs=(Get-ADOrganizationalUnit -Filter *).DistinguishedName
        
        foreach($OU in $OUs)
        {
            DocNumbering -Text $OU -Level 1 -Type Numbered -Heading Heading1 {
     
            $UserInfo=(Get-UserFromOU -OUpath $OU -extended:$false)
                foreach($User in $UserInfo)
                {
                    $hashtable=ConvertTo-Hashtable -Object $User
                    DocTable -DataTable $User -Design ColorfulGridAccent5 -AutoFit Window -OverwriteTitle $User.Name
                    DocText -LineBreak
                    #po userze
                }
            }
        }
        DocText -LineBreak

Without: $hashtable=ConvertTo-Hashtable -Object $User do not work

**Comment by PrzemyslawKlys** [comment]
What does the "do not work" means?

**Comment by oliwex** [comment]
gets table with  transposed data.

**Comment by oliwex** [comment]
(po prostu macierz jest odwrócona o 90 stopni)

**Comment by PrzemyslawKlys** [comment]
```powershell

Documentimo -FilePath $PSScriptRoot\Documentimo-BasicList.docx {
    DocTOC -Title 'Table of content'

    $OUs = Get-ADOrganizationalUnit -Filter * | Select-Object -First 2
    foreach ($OU in $OUs) {
        DocNumbering -Text $OU -Level 1 -Type Numbered -Heading Heading1 {

            $UserInfo = Get-ADUser -Filter * -SearchBase $OU
            foreach ($User in $UserInfo) {
                DocTable -DataTable $User -Design ColorfulGridAccent5 -AutoFit Window
                DocText -LineBreak
            }
        }
    }
    DocText -LineBreak

} -Open
```

Works just fine, each user taken from Get-ADUser is put as a separate table 

![image](https://user-images.githubusercontent.com/15063294/119558082-46ca9d00-bda1-11eb-8a42-ae93cc83f50f.png)

**Comment by oliwex** [comment]
check tomorrow

**Comment by oliwex** [comment]
The expected output:
Name :Jan
Surname Smith
and so on....

in a table
------------------
Name | Jan
------------------
Surname | Smitch
-------------------
.........

**Comment by PrzemyslawKlys** [comment]
So the approach is correct - convert to the hashtable. if you do $USer | ft - it's what you see in Word. There is built-in functionality that transposes table for you. ` -Transpose` parameter does it.

**Comment by PrzemyslawKlys** [comment]
DocTable -Transpose

**Comment by oliwex** [comment]
As simple as that...

**Comment by oliwex** [comment]
It works...thanks
