### ISSUE TITLE
Add image using web URL and Hash table

### ISSUE THREAD

**Issue by ergautamsharma** [EvotecIT/PSWriteWord#62]
Hello, 

I'm stuck with 2 issues while using this PS Module.
1. While I'm adding images in the document using HTTP or HTTPS URL is not working. please advise if this can be done...
2. I used a HASH table with ordered. However, the table in the document is not in ordered as define in the hash table. Please advise on this.

**Comment by PrzemyslawKlys** [comment]
Hi,

1. You can write a function which downloads Image and passes it locally. We could do it inside PSWriteWord - but it's not there yet
2. Do you have a hashtable or ordered hashtable? 

`[ordered] $Table @{ ... }` should work fine. `$Hashtable = @{ ... }` is 50/50 because of it's nature.

**Comment by ergautamsharma** [comment]
Thanks, @PrzemyslawKlys 

I wrote the below lines to use Web image URL, hope you can use it in the "Add-WordPicture" function.
if ($FilePathImage1 -like "http*")
{
    $IMGname = $FilePathImage1 -split "/" | Select-Object -Last 1
    Invoke-WebRequest $FilePathImage1 -OutFile $IMGname
    $FilePathImage1 = $IMGname
}

2. I used the Hash table as below; still, the output is not in the below sequence. Any suggestions?
             $LICHashTable += [ordered]@{ 
                LicenseName = $TextLic; 
                ActiveUnits = $AllLicens.ActiveUnits;
                ConsumedUnits = $AllLicens.ConsumedUnits;
                WarningUnits = $AllLicens.WarningUnits;
            }

**Comment by PrzemyslawKlys** [comment]
$LICHashTable.GetType() - what is the type of this object? I assume $LicHashTable may not be ordered object as it's getting added to existing object.

**Comment by ergautamsharma** [comment]
its Hashtable only as I definied as "**[Collections.Hashtable[]]$LICHashTable = @()**" before the foreach.

below is gettype() output.
Module                     : CommonLanguageRuntimeLibrary
pypeHandle                 : System.RuntimeTypeHandle
BaseType                   : System.Array
UnderlyingSystemType       : System.Collections.Hashtable[]
FullName                   : System.Collections.Hashtable[]
AssemblyQualifiedName      : System.Collections.Hashtable[], mscorlib, 
                             Version=4.0.0.0, Culture=neutral, 
                             PublicKeyToken=b77a5c561934e089
Namespace                  : System.Collections
Name                       : Hashtable[]
MemberType                 : TypeInfo
DeclaredMembers            : {Void Set(Int32, System.Collections.Hashtable), 
                             System.Collections.Hashtable& Address(Int32), 
                             System.Collections.Hashtable Get(Int32), Void 
                             .ctor(Int32)}
DeclaredMethods            : {Void Set(Int32, System.Collections.Hashtable), 
                             System.Collections.Hashtable& Address(Int32), 
                             System.Collections.Hashtable Get(Int32)}
Attributes                 : AutoLayout, AnsiClass, Class, Public, Sealed, 
                             Serializable
IsVisible                  : True
IsPublic                   : True
IsAutoLayout               : True
IsLayoutSequential         : False
IsExplicitLayout           : False
IsClass                    : True
IsAutoClass                : False
IsArray                    : True
HasElementType             : True
CustomAttributes           : {[System.SerializableAttribute()]}

**Comment by ergautamsharma** [comment]
Thanks, @PrzemyslawKlys.

I updated "**[System.Collections.Specialized.OrderedDictionary[]]$LICHashTable = @()**" instead of "**[Collections.Hashtable[]]$LICHashTable = @()**" post its comming as ordered.

is there anyway, while adding the table we can remove the header like Name and Value from the table.

**Comment by PrzemyslawKlys** [comment]
You can overwrite it with a single name.

**Comment by ergautamsharma** [comment]
Please give some examples if possiable.

**Comment by PrzemyslawKlys** [comment]
https://github.com/EvotecIT/PSWriteWord/blob/80897c0a1cd67b0135d33716b677ed414ce07994/Examples/Example-PSWinDocumentation.AD/Starter-AD.ps1#L22

When you use Documentimo "way" it's shown as above

**Comment by ergautamsharma** [comment]
Thanks, @PrzemyslawKlys appreciate your help 🥇 🥇 🥇
