### ISSUE TITLE
Error on UnderlineStyle - seems VSCode specific

### ISSUE THREAD

**Issue by jkavanagh58** [EvotecIT/PSWriteWord#7]
Unable to create document. Error refers to Unable to find type [UnderlineStyle]. The line number it refers to does not exist and UnderlineStyle never called in the script. I copied the full script to ISE and ran debug with no issue. I am running VSCode Insiders  and expecting it more a VSCode issue than the module.

**Comment by PrzemyslawKlys** [comment]
I use VSCode - standard with PowerShell Insiders. Which code are you using? Which functions? Are you using Install-Module or source code version? Underline is in multiple places.

**Comment by PrzemyslawKlys** [comment]
Try new version. I believe I've fixed this.

**Comment by jkavanagh58** [comment]
Actually just  upgraded to 0.4.7 this morning and I am getting this error in VSCode as well as the standard CLI. Now I was using @{ ModuleName="PSWriteWord"; ModuleVersion="0.4.3"} in the Requires statement because what I was using required that version at the time... I removed that and just require based on module name, not version specificity now running without issue. I think closed

**Comment by PrzemyslawKlys** [comment]
Thanks
