### ISSUE TITLE
Add-WordTable: BreakAcrossPages  property not defined?

### ISSUE THREAD

**Issue by oolejniczak** [EvotecIT/PSWriteWord#70]
Add-WordTable -WordDocument $DevicesDOC -DataTable $DeviceDetails.volumes -Design $DocTableTheme -AutoFit Window -Transpose -KeepLinesTogether -BreakAcrossPages $false

return the following error suggesting that the property does not exist

"set-WordTablePageBreak : La propriété « BreakAcrossPages » est introuvable dans cet objet. Vérifiez qu’elle existe et qu’elle peut être définie.
Au caractère C:\Program Files\WindowsPowerShell\Modules\PSWriteWord\1.1.13\PSWriteWord.psm1:2280 : 27
+ ...  = $table | Set-WordTablePageBreak -AfterTable:$BreakPageAfterTable - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [Set-WordTablePageBreak], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException,Set-WordTablePageBreak"

**Comment by PrzemyslawKlys** [comment]
It seems that BreakAcrossPages no longer exists in the library. All I can do is remove this property.
