### ISSUE TITLE
Get-WordDocument -> Error "Load" with "1" argument(s): "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by jojowanuby** [EvotecIT/PSWriteWord#72]
Hi All

I have an issue when opening a specific word file (docx). Strangly All other word files, created from the same .dotx file, work perfectly fine.
The word that causes the error can be opened (word / xml). 
Any ideas on what the problem is or how to fix this?

Skript:
```
$filetemp = "d:\home\site\wwwroot\...\$filenametemp.docx"
$data = Get-WordDocument $filetemp
```

Error in Console:
`[Warning] WARNING: Get-WordDocument - Document: d:\home\site\wwwroot\...\581dd1ca-8a31-4ea0-aeee-8308bd31d1cd.docx Error: Exception calling "Load" with "1" argument(s): "Object reference not set to an instance of an object."`

**Comment by PrzemyslawKlys** [comment]
It's impossible to help with that amount of information.
