### ISSUE TITLE
Document Page Count

### ISSUE THREAD

**Issue by robinsonper** [EvotecIT/PSWriteWord#75]
I know this is not where I should be asking this but I've looked everywhere trying to find help or an answer regarding how to get the number of pages in a word document using PSWriteWord and got nothing. I tried using "Get-WordPageSettings" but it does not contain page count. Is there a way to use any of the Get functions to retrieve the page count on existing documents?

**Comment by PrzemyslawKlys** [comment]
There is no concept of pages in Word OpenXML specification as far as I know in a sense where you can reliably tell on which pages you are unless you really make an effort with page breaks or try to recalculate every single thing within Word which is what most will try to do. You can't create pages or know exactly how many pages there are. 

What happens is once you open Word it does "count" the pages in its own way and saves that value in `ExtendedFilePropertiesPart.Properties.Pages.Text` that can be read. So if the file was created via Word it could be read back, but as mentioned in https://github.com/OfficeDev/Open-XML-SDK/issues/22

> That value is not guaranteed to be correct. In fact, it often will be incorrect. This is one of the issues with Open XML - determining pagination is a big job. (This is true for other document formats, including ODF, not just XML.) Currently, Microsoft's advice is that if you need exact pagination information, you should automate Word.
